spring:
    zipkin:
        base-url: http://localhost:9411
        enabled: true
    sleuth:
        enabled: false
    application:
        name: discovery-server

server:
    port: 8761

eureka:
    instance:
        hostname: localhost
        prefer-ip-address: false
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
    tracing:
        sampling:
            probability: 1.0
    endpoints:
        web:
            exposure:
                include: "*"

logging:
    pattern:
        level: "%5p [${spring.application.name}, %X{traceId:-},%X{spanId:-}]"