apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-deployment
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: ${DOCKER_USERNAME}/discovery-server:latest
        ports:
        - containerPort: 8761 